basePath: /
definitions:
  handlers.AnalysisResult:
    properties:
      data:
        items:
          $ref: '#/definitions/handlers.QueryAnalysis'
        type: array
      error:
        type: string
      status:
        type: string
    type: object
  handlers.CreateUserReq:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  handlers.ErrorEnvelope:
    properties:
      error:
        properties:
          code:
            type: string
          message:
            type: string
        type: object
    type: object
  handlers.LoginReq:
    properties:
      identifier:
        description: username or email
        type: string
      password:
        type: string
    type: object
  handlers.LoginResp:
    properties:
      expires_at:
        type: string
      refresh_expires_at:
        type: string
      refresh_token:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/handlers.UserResp'
    type: object
  handlers.QueryAnalysis:
    properties:
      exec_count:
        type: integer
      exec_time_ms:
        type: integer
      id:
        type: integer
      sql_query:
        type: string
      suggestions:
        type: string
    type: object
  handlers.RefreshReq:
    properties:
      refresh_token:
        type: string
    type: object
  handlers.RefreshResp:
    properties:
      expires_at:
        type: string
      refresh_expires_at:
        type: string
      refresh_token:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/handlers.UserResp'
    type: object
  handlers.RegisterReq:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  handlers.UserResp:
    properties:
      created_by:
        type: string
      created_time:
        type: string
      email:
        type: string
      id:
        type: string
      role:
        type: string
      updated_time:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: REST API demo with auth
  title: go-demo API
  version: "1.0"
paths:
  /healthz:
    get:
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Liveness probe
      tags:
      - platform
  /readyz:
    get:
      responses:
        "200":
          description: ready
          schema:
            type: string
      summary: Readiness probe
      tags:
      - platform
  /v1/admin/users:
    post:
      consumes:
      - application/json
      description: Create a new user with specified role (ADMIN role required)
      parameters:
      - description: Create user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateUserReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.UserResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
      security:
      - BearerAuth: []
      summary: Create user (Admin only)
      tags:
      - admin
  /v1/ai-analysis:
    get:
      parameters:
      - description: Database name
        in: query
        name: db_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AnalysisResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.AnalysisResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.AnalysisResult'
      summary: AI analysis endpoint
      tags:
      - ai
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login with username or email
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LoginResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
      summary: Login
      tags:
      - auth
  /v1/auth/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.UserResp'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - auth
  /v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Exchange refresh token for a new access token (rotation)
      parameters:
      - description: Refresh request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.RefreshReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.RefreshResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
      summary: Refresh access token
      tags:
      - auth
  /v1/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.UserResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorEnvelope'
      summary: Register user
      tags:
      - auth
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
